### ISSUE TITLE
No such file or directory: './asdf/tmp2.jpg'

### ISSUE THREAD

**Issue by rahidz** [HanbumKo/DnCNN-JPEG#1]
When I go to train it (python main.py), this error appears...

```
.../home/rahid/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
GPU

2018-11-20 13:39:06.545468: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-20 13:39:06.547196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.759
pciBusID: 0000:1f:00.0
totalMemory: 5.93GiB freeMemory: 5.71GiB
2018-11-20 13:39:06.547218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-11-20 13:39:06.776509: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-20 13:39:06.776549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-11-20 13:39:06.776555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-11-20 13:39:06.776800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5463 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:1f:00.0, compute capability: 6.1)
[*] Initialize model successfully...
[*] Loading data...
[*] Load successfully...
[*] Reading checkpoint...
[*] Not find pretrained model!
[*] Start training, with start epoch 0 start iter 0 : 
[*] Evaluating...
In __exit__()
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    tf.app.run()
  File "/home/rahid/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 62, in main
    denoiser_train(model, lr=lr)
  File "main.py", line 35, in denoiser_train
    sample_dir=args.sample_dir)
  File "/home/rahid/DnCNN-JPEG/model.py", line 111, in train
    summary_writer=writer)  # eval_data value range is 0-255
  File "/home/rahid/DnCNN-JPEG/model.py", line 57, in evaluate
    noisy_image.save('./asdf/tmp2.jpg', quality=10)
  File "/home/rahid/.local/lib/python3.6/site-packages/PIL/Image.py", line 1947, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './asdf/tmp2.jpg'

```

**Comment by rahidz** [comment]
Created a folder named asdf and that fixed the error. Easy fix :)
